#pragma once

#define ITEM_GRAVITY 0.0007f
#define GAME_UNIT 16.0f

enum class ObjectState {
	UNDEFINED = -1,

	MARIO_STATE_IDLE,
	MARIO_STATE_WALKING_RIGHT,
	MARIO_STATE_WALKING_LEFT,
	MARIO_STATE_JUMP,
	MARIO_STATE_DIE,

	MARIO_TAIL_STATE_IDLE,

	QUESTION_BLOCK_FILLED,
	QUESTION_BLOCK_EMPTY,

	ITEM_VISIBLE,
	ITEM_INVISIBLE,

	GOOMBA_STATE_DIE,
	GOOMBA_STATE_WALKING,

	KOOPAS_STATE_DIE,
	KOOPAS_STATE_WALKING,

};

typedef ObjectState State;